Skeleton
js-tasks-ru/htmlcss-20220616_bronnikov-aleks pull request #7
Opened 2022-07-10 13:34 UTC by MasamuneBALEX

2022-07-10 13:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-11 08:57 UTC, GSemikozov requested changes

2022-07-11 08:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__info-1 {
имена классов по типу info-1 / info-2 / block-1 очень не информативные и из названия классов неясно о какой части компонента идет речь, тут лучше более семантичные классы по типу .skeleton__top / .skeleton__bottom, .skeleton__top-column

2022-07-11 08:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__block-1 {
можно обойтись без этого лишнего враппера + у div и так по умолчанию display: block

2022-07-11 08:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__block-2 {
.skeleton__top-info

2022-07-11 08:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                    <div style="width: 50%;" class="skeleton__line"></div>
вместо инлайна лучше классы-модификаторы которые будут менять ширину - skeleton__line_short, skeleton__line_middle и тд

2022-07-11 14:08 UTC, MasamuneBALEX commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__info-1 {
Хорошо, исправлю

2022-07-11 14:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-11 14:44 UTC, GSemikozov approved these changes

2022-07-11 14:44 UTC, merged